#!/usr/bin/env bash

if
  [[ -s ".rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/environment" ]]
then
  source ".rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/environment"
  exec testrb "$@"
else
  echo "ERROR: Missing RVM environment file: '.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/environment'" >&2
  exit 1
fi
